Mw_ES_ILE_N1
Mw_ES_MET_N1
Mw_ES_CYS_N1
Gs(U)_ES_PRT_TI50
Pa_ES_NPR_TI50
ISA_ES_NPR_TI50
ECI_ES_PRT_TI50
Z3_ES_BSR_TI50
Gw(U)_ES_PRT_TI50
IP_ES_GLY_TI50
Mw_ES_ILE_N2
W(U)_ES_ALA_TI50
Pt_ES_ARG_SI50
W(U)_ES_PHE_SI50
Pa_ES_PHE_SI50
Pt_ES_PCR_SI50
IP_ES_GLY_SI50
Ap_ES_PCR_TI50
IP_ES_AHR_TI50
W(U)_ES_CYS_N2
Mw_ES_ALR_MI50
Pb_ES_MET_SI50
